name: ML Model - 3 Hyperparameter Tuning per Model

on:
  push:
    branches: [ reg_branch ]

jobs:
  train:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.5'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r HousingRegression/requirements.txt || echo "Installation failed, check logs"

      - name: List directory
        run: |
          dir

      - name: Train and Evaluate models
        run: |
          python HousingRegression/main.py